### ISSUE TITLE
APPLICATION FAILED TO START

### ISSUE THREAD

**Issue by vsingh-solenis** [SoftwareAG/cumulocity-microservice-templates#18]
I  have  build  parent  pom  and  import  in eclipse.after  trying cumulocity-microservice-templates-realtime Project using  mvn spring-boot:run i  am  getting  below  error

***************************
APPLICATION FAILED TO START
***************************

Description:

Field platform in com.c8y.ms.templates.realtime.controller.NotificationController required a bean of type 'com.cumulocity.sdk.client.PlatformImpl' that could not be found.

Action:

Bean of this type is no longer available.
Instead inject platform APIs directly or inject com.cumulocity.sdk.client.Platform and get the same platform APIs instances with getters.
Use relative URL's starting with '/' with RestConnector bean to have them resolved automatically against the host defined in PlatformParameters#getHost().

**Comment by PestusAtSAG** [comment]
Yes, correct, with new Version of SDK, class is not available anymore com.cumulocity.sdk.client.PlatformImpl
I will check and find solution for that. Thank you for raising that issue.

**Comment by haraldmeyer** [comment]
@vsingh-solenis this is fixed now.
